### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by Baldwinzc** [the-username-is-available/tmegl-v1#1]
Dear professor,

Thank you for your outstanding work! I found it truly fascinating to read through your research.

I have a question that I hope you can help clarify:

Based on the source code, it seems that "lbls" and "survtimes" are attributes of the graph. I’m not sure if my understanding is correct. Also, what does "ls" mean in the code?

Thank you in advance for your assistance!
![1730727930025](https://github.com/user-attachments/assets/cbf1f2e1-d334-4c27-afda-276912ee211d)

**Comment by wkmyws** [comment]
you are right, `lbls` and `survtimes` are attributes of the graph.

And `info["ls"]` is the address where the data folder stored locally is recorded. This is some dirty work in data processing, used to extract `tags` and some other information from raw data, and is not important, eg.
```python
ls = sorted(os.listdir(folder_path) if isinstance(folder_path, str) else folder_path)
ls = [os.path.join(folder_path, i) for i in ls] if isinstance(folder_path, str) else ls # get file path
origin_tags = ["-".join(os.path.split(sample)[-1].split("-")[0:3]) for sample in ls] # extract tag from file path name
```
